# AIRMSPI Configuration
# Base parameters
IF_AIRMSPI: True
IF_NEW_TXT: False
n_jobs: 1
maxiter: 150
stokes: ['I', 'Q', 'U']
max_simultaneous_simulations: 1  # how many clouds running in parallel
IS_SUN_CONST: 1
cancel_noise: False

# AIRMSPI-specific parameters
wavelengths: [[0.660, 0.660]]
radiance_thresholds: [0.028, 0.025, 0.025, 0.025, 0.024, 0.023, 0.022, 0.024, 0.025]
images_path_for_nn: '/wdata_visl/inbalkom/NN_Data/BOMEX_256x256x100_5000CCN_50m_micro_256/AIRMSPI_SIMULATIONS_AT3D/'
Lat_for_sun_angles: 32  # degrees
const_sun_azimuth: 36.56
const_sun_zenith: 154.74

