# Modified by Roi Ronen. Originally created by Yael Sde-Chen for 3DeepCT project
# ------------------------------------------------------------
# This file is kept for reference but most parameters have been moved to:
# - configs/params_airmspi.yaml (AIRMSPI-specific configuration)
# - configs/params_cloudct.yaml (CloudCT-specific configuration)
# ------------------------------------------------------------

# --------------------------------------------------
# --------   CloudCT neural network  ---------------
# --------------------------------------------------
# neural_network:
#   satellites_images_path:  "/media/roironen/8AAE21F5AE21DB09/Data"

# --------------------------------------------------
# -------------   Simulation flags  ----------------
# --------------------------------------------------
# DOFORWARD: True
# DOINVERSE: False

# --------------------------------------------------
# --------------   Use Simple Imager?  --------------
# --------------------------------------------------
# USE_SIMPLE_IMAGER: True
# if it's true, the imager is simple and not loaded from the imagers data set.


# --------------------------------------------------
# ------------   VIS Imager Parameters  ------------
# --------------------------------------------------
# temperature: &temperature 15
# vis_options:
#   ImportConfigPath: '../notebooks/Gecko_config.json'
#   temperature: *temperature # celsius
#   #true_indices: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31]  # where imagers are located
#   rays_per_pixel: 1
#   rigid_sampling: True

# --------------------------------------------------
# ------------   SWIR Imager Parameters  ------------
# --------------------------------------------------
# swir_options:
#   ImportConfigPath: '../notebooks/Hypothetic_SWIR_camera_config_50m_nadir_resolution.json'
#   temperature: *temperature # celsius
#   true_indices: []   # where imagers are located, if true_indices: [], no swir imager will be simulated
#   rays_per_pixel: 1
#   rigid_sampling: True


# --------------------------------------------------
# -------------   Cloud & Air Field files  ---------
# --------------------------------------------------
# CloudFieldFile: '/media/roironen/8AAE21F5AE21DB09/Data/clouds/cloud{CLOUD_INDEX}.txt'
# AirFieldFile: '../ancillary_data/AFGL_summer_mid_lat.txt'  # Path to csv file which contains temperature measurements


# --------------------------------------------------
# ----------------  Number of Jobs  ----------------
# --------------------------------------------------
# n_jobs: 72  # Now in params_airmspi.yaml or params_cloudct.yaml


# --------------------------------------------------
# ----------------   Orbit and GSD  ----------------
# --------------------------------------------------
# Rsat: 500  # orbit altitude, km - Now in params_cloudct.yaml
# GSD: 0.02  # in km, it is the ground spatial resolution. - Now in params_cloudct.yaml
# dx: 50
# dy: 50
# dz: 50
# n_formations: 10

# --------------------------------------------------
# -----------------   Wavelengths  -----------------
# --------------------------------------------------
# (Now in params_airmspi.yaml or params_cloudct.yaml)


# --------------------------------------------------
# -------------   Sun Azimuth & Zenith  ------------
# --------------------------------------------------
# sun_azimuth: 45  # azimuth: 0 is beam going in positive X direction (North), 90 is positive Y (East). - Now in config files
# sun_zenith: 150  # zenith: Solar beam zenith angle in range (90,180] - Now in config files


# --------------------------------------------------
# ------------   Number of Satellites  -------------
# --------------------------------------------------
# SATS_NUMBER_SETUP: &num_sats 10  # satellites number to build the setup, for the inverse, we can use less satellites. - Now in params_cloudct.yaml
# SATS_NUMBER_INVERSE: *num_sats  #10, how much satellites will be used for the inverse.


# --------------------------------------------------
# ---------  numerical & scene Parameters  ---------
# ---------  for RTE solver & solver init  ---------
# --------------------------------------------------
# later we must update it since it depends on the wavelegth.
# split_accuracy of 0.1 gives nice results, For the rico cloud i didn't see that decreasing the split accuracy improves the rec.
# so fo the rico loud Let's use split_accuracy = 0.1.
# solar_fluxes_val: 1.0
# split_accuracies_val: 0.1
# surface_albedos_val: 0.05

# --------------------------------------------------
# -------------   Radiance Threshold  ------------
# --------------------------------------------------
# radiance_threshold: 0.02 # Threshold is either a scalar or a list of length of measurements. - Now in config files


# -------------------------------------------------
# -------------   mia table parameters  -----------
# -------------------------------------------------
# mie_options:
#   start_reff: 1 # Starting effective radius [Micron]
#   end_reff: 35.0
#   num_reff: 100
#   start_veff: 0.01
#   end_veff: 0.4 # return it to 0.4
#   num_veff: 117
#   radius_cutoff: 65.0 # The cutoff radius for the pdf averaging [Micron]
#   wavelength_resolution: 0.001 # it is the delta in the wavelengths (microns) for the optical parameters avaraging inside shdom.


# -------------------------------------------------
# -----------  Visualization parameters  ----------
# -------------------------------------------------
# vizual_options:
#   VISSETUP: False
#   CENCEL_AIR: False # just for debugging, in runtime  must be false.
#   scale: 500
#   axisWidth: 0.02
#   axisLenght: 5000


# -------------------------------------------------
# ----------------  Forward parameters  -----------
# -------------------------------------------------
# forward_options:
#   SEE_IMAGES: False
#   temp: 5900  # K,  units of W/(m^2))
#   num_mu: 8
#   num_phi: 16
#   max_total_mb: 100000.0
#   rte_solver_max_iter: 100 # max number of iterations for rte solver
#   solar_fluxes: [1, 1]  # unity flux, IT IS IMPORTANT HERE!
#   split_accuracies: [0.1, 0.1] # 0.1 gives nice results, For the rico cloud i didn't see that decreasing the split accuracy improves the rec.
#                                # so fo the rico loud Let's use split_accuracy = 0.1.
#   surface_albedos: [0.05, 0.05]  # later we must update it since it depends on the wavelegth.
#   adapt_grid_factor: 5  # TODO not in use
#   solution_accuracy: 0.0001  # TODO not in use


# -------------------------------------------------
# ----------------  inverse parameters  -----------
# -------------------------------------------------
# inverse_options:
#   SEE_SETUP: False
#   SEE_IMAGES: False
#   VIS_RESULTS3D: True  # show the results in 3D visualization
#   MICROPHYSICS: False
#   recover_type: 'lwc' # expects: one of 'lwc' / 'reff' / 'veff' / 'reff_and_lwc'
#   lwc: 0.01  # init lwc of the generator
#   reff: 12 # init reff of the generator
#   veff: 0.19 # init veff of the generator
#   lwc_scaling_val: 15
#   reff_scaling_val: 0.01
#   extinction: 0.01  # init extinction of the generator
#   scripts_path: '../scripts'
#   stokes_weights: [1.0, 0.0, 0.0, 0.0] # Loss function weights for stokes vector components [I, Q, U, V]
#   init: 'Homogeneous' # init_generator = 'Homogeneous' it is the CloudGenerator from shdom.generate.py
#   add_rayleigh: True
#   use_forward_mask: False
#   use_forward_grid: True
#   cloudct_use: False
#   use_forward_albedo: False
#   use_forward_phase: False
#   if_save_gt_and_carver_masks: True
#   if_save_final3d: True
#   globalopt: False  # Global optimization with basin-hopping
#   maxiter: 1  # Maximum number of L-BFGS iterations
#   maxls: 30  # Maximum number of line search steps (per iteration)
#   disp: True  # Display optimization progression
#   gtol: 1e-16  # Stop criteria for the maximum projected gradient
#   ftol: 1e-16  # Stop criteria for the relative change in loss function
#   loss_type: 'l2'  # Different loss functions for optimization. Currently only l2 is supported
#   extinction_optimizer: 'optimize_extinction_lbfgs.py'
#   microphysics_optimizer: 'optimize_microphysics_lbfgs.py'

# ----------------------------------------------
# -------------------  Others  -----------------
# ----------------------------------------------
# Sometimes it is more convenient to use wide fov to see the whole cloud from all the view points.
# so the FOV is also tuned:
# IFTUNE_CAM: True  # Now handled in code